# version: '3'

services:
  # app:
  #   build: 
  #     context: ..
  #     dockerfile: .
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=test
  #     - MYSQL_USER=talend
  #     - MYSQL_PASSWORD=talend      

  #   depends_on:
  #     - mysql 


  mysql:
    image: mysql:8.0.41
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=talend
      - MYSQL_PASSWORD=talend
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql --local-infile=1
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   
      - ./:/local/
      - db-volume2:/var/lib/mysql


  vault:
    image: hashicorp/vault:1.18
    container_name: vault_container
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
    ports:
      - "8200:8200"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/file:/vault/file   
         
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_USER=talend
  #     - POSTGRES_PASSWORD=talend
  #     - POSTGRES_DB=talend
  #   ports:
  #     - "5432:5432"

  # mariadb:
  #   image: mariadb:latest
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=root
  #     - MARIADB_DATABASE=test
  #     - MARIADB_USER=talend
  #     - MARIADB_PASSWORD=talend
  #   ports:
  #     - "3307:3307"
  #   command: --init-file /docker-entrypoint-initdb.d/init.sql
  #   volumes:
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql            


volumes:
    db-volume2:  