# version: '3'

services:
  # app:
  #   build: 
  #     context: ..
  #     dockerfile: .
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=test
  #     - MYSQL_USER=talend
  #     - MYSQL_PASSWORD=talend      

  #   depends_on:
  #     - mysql 


  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=talend
      - MYSQL_PASSWORD=talend
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   
      - ./:/local/

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_USER=talend
  #     - POSTGRES_PASSWORD=talend
  #     - POSTGRES_DB=talend
  #   ports:
  #     - "5432:5432"

  # mariadb:
  #   image: mariadb:latest
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=root
  #     - MARIADB_DATABASE=test
  #     - MARIADB_USER=talend
  #     - MARIADB_PASSWORD=talend
  #   ports:
  #     - "3307:3307"
  #   command: --init-file /docker-entrypoint-initdb.d/init.sql
  #   volumes:
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql            